/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as RestablecerPasswordRouteImport } from './routes/restablecer-password'
import { Route as RegistroRouteImport } from './routes/registro'
import { Route as PlanesRouteImport } from './routes/planes'
import { Route as PanelRouteImport } from './routes/panel'
import { Route as OlvidePasswordRouteImport } from './routes/olvide-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as CursosRouteImport } from './routes/cursos'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as ComunidadRouteImport } from './routes/comunidad'
import { Route as AdminLoginRouteImport } from './routes/admin-login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VerSlugRouteImport } from './routes/ver.$slug'
import { Route as CursoSlugRouteImport } from './routes/curso.$slug'
import { Route as CertificadoSlugRouteImport } from './routes/certificado.$slug'
import { Route as PagoparResultadoHashRouteImport } from './routes/pagopar/resultado.$hash'
import { Route as CursoSlugTeoriaRouteImport } from './routes/curso.$slug_.teoria'

const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const RestablecerPasswordRoute = RestablecerPasswordRouteImport.update({
  id: '/restablecer-password',
  path: '/restablecer-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistroRoute = RegistroRouteImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanesRoute = PlanesRouteImport.update({
  id: '/planes',
  path: '/planes',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelRoute = PanelRouteImport.update({
  id: '/panel',
  path: '/panel',
  getParentRoute: () => rootRouteImport,
} as any)
const OlvidePasswordRoute = OlvidePasswordRouteImport.update({
  id: '/olvide-password',
  path: '/olvide-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const CursosRoute = CursosRouteImport.update({
  id: '/cursos',
  path: '/cursos',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const ComunidadRoute = ComunidadRouteImport.update({
  id: '/comunidad',
  path: '/comunidad',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin-login',
  path: '/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerSlugRoute = VerSlugRouteImport.update({
  id: '/ver/$slug',
  path: '/ver/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CursoSlugRoute = CursoSlugRouteImport.update({
  id: '/curso/$slug',
  path: '/curso/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificadoSlugRoute = CertificadoSlugRouteImport.update({
  id: '/certificado/$slug',
  path: '/certificado/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PagoparResultadoHashRoute = PagoparResultadoHashRouteImport.update({
  id: '/pagopar/resultado/$hash',
  path: '/pagopar/resultado/$hash',
  getParentRoute: () => rootRouteImport,
} as any)
const CursoSlugTeoriaRoute = CursoSlugTeoriaRouteImport.update({
  id: '/curso/$slug_/teoria',
  path: '/curso/$slug/teoria',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-login': typeof AdminLoginRoute
  '/comunidad': typeof ComunidadRoute
  '/contacto': typeof ContactoRoute
  '/cursos': typeof CursosRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/olvide-password': typeof OlvidePasswordRoute
  '/panel': typeof PanelRoute
  '/planes': typeof PlanesRoute
  '/registro': typeof RegistroRoute
  '/restablecer-password': typeof RestablecerPasswordRoute
  '/sobre': typeof SobreRoute
  '/certificado/$slug': typeof CertificadoSlugRoute
  '/curso/$slug': typeof CursoSlugRoute
  '/ver/$slug': typeof VerSlugRoute
  '/curso/$slug/teoria': typeof CursoSlugTeoriaRoute
  '/pagopar/resultado/$hash': typeof PagoparResultadoHashRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-login': typeof AdminLoginRoute
  '/comunidad': typeof ComunidadRoute
  '/contacto': typeof ContactoRoute
  '/cursos': typeof CursosRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/olvide-password': typeof OlvidePasswordRoute
  '/panel': typeof PanelRoute
  '/planes': typeof PlanesRoute
  '/registro': typeof RegistroRoute
  '/restablecer-password': typeof RestablecerPasswordRoute
  '/sobre': typeof SobreRoute
  '/certificado/$slug': typeof CertificadoSlugRoute
  '/curso/$slug': typeof CursoSlugRoute
  '/ver/$slug': typeof VerSlugRoute
  '/curso/$slug/teoria': typeof CursoSlugTeoriaRoute
  '/pagopar/resultado/$hash': typeof PagoparResultadoHashRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-login': typeof AdminLoginRoute
  '/comunidad': typeof ComunidadRoute
  '/contacto': typeof ContactoRoute
  '/cursos': typeof CursosRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/olvide-password': typeof OlvidePasswordRoute
  '/panel': typeof PanelRoute
  '/planes': typeof PlanesRoute
  '/registro': typeof RegistroRoute
  '/restablecer-password': typeof RestablecerPasswordRoute
  '/sobre': typeof SobreRoute
  '/certificado/$slug': typeof CertificadoSlugRoute
  '/curso/$slug': typeof CursoSlugRoute
  '/ver/$slug': typeof VerSlugRoute
  '/curso/$slug_/teoria': typeof CursoSlugTeoriaRoute
  '/pagopar/resultado/$hash': typeof PagoparResultadoHashRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin-login'
    | '/comunidad'
    | '/contacto'
    | '/cursos'
    | '/faq'
    | '/login'
    | '/olvide-password'
    | '/panel'
    | '/planes'
    | '/registro'
    | '/restablecer-password'
    | '/sobre'
    | '/certificado/$slug'
    | '/curso/$slug'
    | '/ver/$slug'
    | '/curso/$slug/teoria'
    | '/pagopar/resultado/$hash'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/admin-login'
    | '/comunidad'
    | '/contacto'
    | '/cursos'
    | '/faq'
    | '/login'
    | '/olvide-password'
    | '/panel'
    | '/planes'
    | '/registro'
    | '/restablecer-password'
    | '/sobre'
    | '/certificado/$slug'
    | '/curso/$slug'
    | '/ver/$slug'
    | '/curso/$slug/teoria'
    | '/pagopar/resultado/$hash'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin-login'
    | '/comunidad'
    | '/contacto'
    | '/cursos'
    | '/faq'
    | '/login'
    | '/olvide-password'
    | '/panel'
    | '/planes'
    | '/registro'
    | '/restablecer-password'
    | '/sobre'
    | '/certificado/$slug'
    | '/curso/$slug'
    | '/ver/$slug'
    | '/curso/$slug_/teoria'
    | '/pagopar/resultado/$hash'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AdminLoginRoute: typeof AdminLoginRoute
  ComunidadRoute: typeof ComunidadRoute
  ContactoRoute: typeof ContactoRoute
  CursosRoute: typeof CursosRoute
  FaqRoute: typeof FaqRoute
  LoginRoute: typeof LoginRoute
  OlvidePasswordRoute: typeof OlvidePasswordRoute
  PanelRoute: typeof PanelRoute
  PlanesRoute: typeof PlanesRoute
  RegistroRoute: typeof RegistroRoute
  RestablecerPasswordRoute: typeof RestablecerPasswordRoute
  SobreRoute: typeof SobreRoute
  CertificadoSlugRoute: typeof CertificadoSlugRoute
  CursoSlugRoute: typeof CursoSlugRoute
  VerSlugRoute: typeof VerSlugRoute
  CursoSlugTeoriaRoute: typeof CursoSlugTeoriaRoute
  PagoparResultadoHashRoute: typeof PagoparResultadoHashRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restablecer-password': {
      id: '/restablecer-password'
      path: '/restablecer-password'
      fullPath: '/restablecer-password'
      preLoaderRoute: typeof RestablecerPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registro': {
      id: '/registro'
      path: '/registro'
      fullPath: '/registro'
      preLoaderRoute: typeof RegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planes': {
      id: '/planes'
      path: '/planes'
      fullPath: '/planes'
      preLoaderRoute: typeof PlanesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panel': {
      id: '/panel'
      path: '/panel'
      fullPath: '/panel'
      preLoaderRoute: typeof PanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/olvide-password': {
      id: '/olvide-password'
      path: '/olvide-password'
      fullPath: '/olvide-password'
      preLoaderRoute: typeof OlvidePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cursos': {
      id: '/cursos'
      path: '/cursos'
      fullPath: '/cursos'
      preLoaderRoute: typeof CursosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comunidad': {
      id: '/comunidad'
      path: '/comunidad'
      fullPath: '/comunidad'
      preLoaderRoute: typeof ComunidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-login': {
      id: '/admin-login'
      path: '/admin-login'
      fullPath: '/admin-login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ver/$slug': {
      id: '/ver/$slug'
      path: '/ver/$slug'
      fullPath: '/ver/$slug'
      preLoaderRoute: typeof VerSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curso/$slug': {
      id: '/curso/$slug'
      path: '/curso/$slug'
      fullPath: '/curso/$slug'
      preLoaderRoute: typeof CursoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificado/$slug': {
      id: '/certificado/$slug'
      path: '/certificado/$slug'
      fullPath: '/certificado/$slug'
      preLoaderRoute: typeof CertificadoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagopar/resultado/$hash': {
      id: '/pagopar/resultado/$hash'
      path: '/pagopar/resultado/$hash'
      fullPath: '/pagopar/resultado/$hash'
      preLoaderRoute: typeof PagoparResultadoHashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curso/$slug_/teoria': {
      id: '/curso/$slug_/teoria'
      path: '/curso/$slug/teoria'
      fullPath: '/curso/$slug/teoria'
      preLoaderRoute: typeof CursoSlugTeoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AdminLoginRoute: AdminLoginRoute,
  ComunidadRoute: ComunidadRoute,
  ContactoRoute: ContactoRoute,
  CursosRoute: CursosRoute,
  FaqRoute: FaqRoute,
  LoginRoute: LoginRoute,
  OlvidePasswordRoute: OlvidePasswordRoute,
  PanelRoute: PanelRoute,
  PlanesRoute: PlanesRoute,
  RegistroRoute: RegistroRoute,
  RestablecerPasswordRoute: RestablecerPasswordRoute,
  SobreRoute: SobreRoute,
  CertificadoSlugRoute: CertificadoSlugRoute,
  CursoSlugRoute: CursoSlugRoute,
  VerSlugRoute: VerSlugRoute,
  CursoSlugTeoriaRoute: CursoSlugTeoriaRoute,
  PagoparResultadoHashRoute: PagoparResultadoHashRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
